CREATE TABLE Students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255),
    middleName VARCHAR(255),
    lastName VARCHAR(255),
    course VARCHAR(100),
    yearLevel INT,
    semester INT,
    dateOfBirth DATE,
    sex VARCHAR(10),
    citizenship VARCHAR(100),
    contactNumber VARCHAR(20),
    email VARCHAR(100),
    provinceAddress VARCHAR(255),
    cityAddress VARCHAR(255),
    barangayAddress VARCHAR(255),
    streetAddress VARCHAR(255),
    zipCode VARCHAR(10),
    religion VARCHAR(100),
    studentType VARCHAR(100),
    emergencyContactFirstName VARCHAR(255),
    emergencyContactMiddleName VARCHAR(255),
    emergencyContactLastName VARCHAR(255),
    emergencyContactDob DATE,
    emergencyContactRelationship VARCHAR(100),
    emergencyContactPhone VARCHAR(20),
    emergencyContactEmail VARCHAR(100)
);
